{DEFAULT @CDM_schema = 'Alligator_CDM4_All'}
{DEFAULT @HTN_Combi = 'SJ_HTN_combi'}
{DEFAULT @HTN_Combi_code = 'Chan_HTN_Combi'}

USE [@HTN_Combi];

-- HTN medication list
SELECT * FROM [@HTN_combi_code].[dbo].HTN_med
SELECT DISTINCT DRUG_CLASS FROM [@HTN_combi_code].[dbo].HTN_med ORDER BY DRUG_CLASS

-- VISIT
SELECT TOP 10 * FROM [@CDM_schema].[dbo].VISIT_OCCURRENCE

-- DRUG
SELECT TOP 10 * FROM [@CDM_schema].[dbo].DRUG_EXPOSURE

-- DRUG HISTORY IN MEDICATION LIST
--(1919094 row(s) affected)
IF OBJECT_ID('[@HTN_combi].[dbo].DRUG_HISTORY_STEP1', 'U') IS NOT NULL
	DROP TABLE DRUG_HISTORY_STEP1;
SELECT *, ROW_NUMBER() OVER(PARTITION BY PERSON_ID, DRUG_CLASS_SIMPLE ORDER BY DRUG_START_DATE, DRUG_END_DATE, DAYS_SUPPLY DESC) DRUG_SEQ
INTO DRUG_HISTORY_STEP1
FROM (
		SELECT *
		FROM (
			SELECT DISTINCT BB.*
				, DATEDIFF(YY, AA.BIRTHDAY, BB.DRUG_START_DATE) -
				CASE WHEN DATEADD(YY, DATEDIFF(YY, AA.BIRTHDAY, BB.DRUG_START_DATE), AA.BIRTHDAY)
							> BB.DRUG_START_DATE THEN 1
					ELSE 0
				END AGE
			FROM (
				SELECT DISTINCT PERSON_ID
					, CAST(
						CAST(YEAR_OF_BIRTH AS VARCHAR(4))+
						RIGHT('0'+CAST(MONTH_OF_BIRTH AS VARCHAR(2)),2)+
						RIGHT('0'+CAST(DAY_OF_BIRTH AS VARCHAR(2)),2) 
						AS DATETIME
					) BIRTHDAY
				FROM [@CDM_schema].[dbo].PERSON	
			) AA
			INNER JOIN (
				SELECT PERSON_ID, DRUG_CONCEPT_ID, CAST(DRUG_EXPOSURE_START_DATE AS DATE) DRUG_START_DATE, CAST(DRUG_EXPOSURE_END_DATE AS DATE) DRUG_END_DATE, QUANTITY, DAYS_SUPPLY
				FROM [@CDM_schema].[dbo].DRUG_EXPOSURE
				WHERE DAYS_SUPPLY>=7
			) BB
			ON AA.PERSON_ID=BB.PERSON_ID
		) T
		WHERE AGE IS NOT NULL
			AND AGE>=20
	) A
	INNER JOIN 
	(
		SELECT *, UPPER(SUBSTRING(DRUG_CLASS, 1,1)) DRUG_CLASS_SIMPLE
		FROM [@HTN_combi_code].[dbo].HTN_med
	) B
	ON A.DRUG_CONCEPT_ID=B.CONCEPT_ID

SELECT * FROM DRUG_HISTORY_STEP1 ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_SEQ

-- DRUG HISTORY EXTENDDATE
--(1919094 row(s) affected)
IF OBJECT_ID('[@HTN_combi].[dbo].DRUG_HISTORY_STEP2', 'U') IS NOT NULL
	DROP TABLE DRUG_HISTORY_STEP2;
SELECT T1.*, T2.DRUG_END_DATE DRUG_EXT_END_DATE
INTO DRUG_HISTORY_STEP2
FROM DRUG_HISTORY_STEP1 T1
	OUTER APPLY(
		SELECT TOP 1 *
		FROM DRUG_HISTORY_STEP1
		WHERE PERSON_ID=T1.PERSON_ID
			AND DRUG_CLASS_SIMPLE=T1.DRUG_CLASS_SIMPLE
			AND DRUG_SEQ<=T1.DRUG_SEQ
			AND DRUG_END_DATE>=T1.DRUG_END_DATE
		ORDER BY DRUG_END_DATE DESC
	) T2
--ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_SEQ

SELECT * FROM DRUG_HISTORY_STEP2 ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_SEQ

-- DRUG HISTORY DAYDIFF END-START
--(1919094 row(s) affected)
IF OBJECT_ID('[@HTN_combi].[dbo].DRUG_HISTORY_STEP3', 'U') IS NOT NULL
	DROP TABLE DRUG_HISTORY_STEP3;
SELECT A.PERSON_ID, A.DRUG_CLASS_SIMPLE, A.DRUG_SEQ, A.DRUG_START_DATE, A.DRUG_EXT_END_DATE
	, DATEDIFF(DAY, B.DRUG_EXT_END_DATE, A.DRUG_START_DATE) AS DAYDIFF_END_START
INTO DRUG_HISTORY_STEP3
FROM DRUG_HISTORY_STEP2 A LEFT JOIN DRUG_HISTORY_STEP2 B
	ON A.PERSON_ID=B.PERSON_ID
		AND A.DRUG_CLASS_SIMPLE=B.DRUG_CLASS_SIMPLE
		AND A.DRUG_SEQ = CAST(B.DRUG_SEQ AS INT) +1
--ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_SEQ

SELECT * FROM DRUG_HISTORY_STEP3 ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_SEQ

-- DRUG HISTORY GRACE PERIOD 14 DAYS
--(1919094 row(s) affected)
IF OBJECT_ID('[@HTN_combi].[dbo].DRUG_HISTORY_STEP4', 'U') IS NOT NULL
	DROP TABLE DRUG_HISTORY_STEP4;
SELECT *, CASE
	WHEN DRUG_SEQ=1 THEN 1
	ELSE SUM(CASE WHEN DAYDIFF_END_START>=14 THEN 1 ELSE 0 END) OVER(PARTITION BY PERSON_ID, DRUG_CLASS_SIMPLE ORDER BY DRUG_SEQ ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)+1
	END AS DRUG_FU_SEQ
INTO DRUG_HISTORY_STEP4
FROM DRUG_HISTORY_STEP3
--ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_SEQ

SELECT * FROM DRUG_HISTORY_STEP4 ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_SEQ

-- DRUG HISTORY CONTINUOUS PRESCRIPTIONS
--(450954 row(s) affected) ? 504051
IF OBJECT_ID('[@HTN_combi].[dbo].DRUG_HISTORY_STEP5', 'U') IS NOT NULL
	DROP TABLE DRUG_HISTORY_STEP5;
SELECT PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_FU_SEQ
	, MIN(DRUG_START_DATE) AS MIN_START_DATE
	, MAX(DRUG_EXT_END_DATE) AS MAX_END_DATE
	, MAX(DRUG_START_DATE) AS LAST_DRUG_START_DATE
	, COUNT(*) AS CNT
INTO DRUG_HISTORY_STEP5
FROM DRUG_HISTORY_STEP4
GROUP BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_FU_SEQ

SELECT * FROM DRUG_HISTORY_STEP5 ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_FU_SEQ

-- DRUG HISTORY CONTINUOUS DATEDIFF MAXEND-MINSTART
--(450954 row(s) affected)
IF OBJECT_ID('[@HTN_combi].[dbo].DRUG_HISTORY_STEP6', 'U') IS NOT NULL
	DROP TABLE DRUG_HISTORY_STEP6;
SELECT PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_FU_SEQ, MIN_START_DATE, MAX_END_DATE, LAST_DRUG_START_DATE
	, DATEDIFF(DAY, MIN_START_DATE, MAX_END_DATE) AS CONT_DAYS
INTO DRUG_HISTORY_STEP6
FROM DRUG_HISTORY_STEP5

SELECT * FROM DRUG_HISTORY_STEP6 ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_FU_SEQ
SELECT * FROM DRUG_HISTORY_STEP6 ORDER BY DRUG_CLASS_SIMPLE, PERSON_ID, DRUG_FU_SEQ

-- DRUG HISTORY CONTINUOUS 90 DAYS
--(246063 row(s) affected)
IF OBJECT_ID('[@HTN_combi].[dbo].DRUG_HISTORY_STEP7', 'U') IS NOT NULL
	DROP TABLE DRUG_HISTORY_STEP7;
SELECT PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_FU_SEQ, MIN_START_DATE, MAX_END_DATE, LAST_DRUG_START_DATE, CONT_DAYS
INTO DRUG_HISTORY_STEP7
FROM DRUG_HISTORY_STEP6
WHERE CONT_DAYS>=90

SELECT * FROM DRUG_HISTORY_STEP7 ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_FU_SEQ
SELECT * FROM DRUG_HISTORY_STEP7 ORDER BY DRUG_CLASS_SIMPLE, PERSON_ID, DRUG_FU_SEQ

-- DRUG HISTORY SUPPLY 7DAYS CONTINUOUS 90 DAYS GRACE 14 DAYS
--(248433 row(s) affected)
IF OBJECT_ID('[@HTN_combi].[dbo].DRUG_HISTORY_S7D_G14D_C90D', 'U') IS NOT NULL
	DROP TABLE DRUG_HISTORY_S7D_G14D_C90D;
SELECT *
INTO DRUG_HISTORY_S7D_G14D_C90D
FROM DRUG_HISTORY_STEP7

----- temp
SELECT TOP 100 * FROM DRUG_HISTORY_STEP1 ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_SEQ
SELECT TOP 100 * FROM DRUG_HISTORY_STEP2 ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_SEQ
SELECT TOP 100 * FROM DRUG_HISTORY_STEP3 ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_SEQ
SELECT TOP 100 * FROM DRUG_HISTORY_STEP4 ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_SEQ
SELECT TOP 100 * FROM DRUG_HISTORY_STEP5 ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_FU_SEQ
SELECT TOP 100 * FROM DRUG_HISTORY_STEP6 ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_FU_SEQ
SELECT TOP 100 * FROM DRUG_HISTORY_STEP7 ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_FU_SEQ

SELECT TOP 1000 * FROM DRUG_HISTORY_S7D_G14D_C90D ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_FU_SEQ
SELECT TOP 1000 * FROM DRUG_HISTORY_STEP6 ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_FU_SEQ
SELECT * FROM DRUG_HISTORY_S7D_G14D_C90D ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_FU_SEQ
SELECT * FROM DRUG_HISTORY_STEP6 ORDER BY PERSON_ID, DRUG_CLASS_SIMPLE, DRUG_FU_SEQ
SELECT COUNT(DISTINCT PERSON_ID) FROM DRUG_HISTORY_S7D_G14D_C90D
