covSettings <- FeatureExtraction::createCovariateSettings(useCovariateDemographics = TRUE, useCovariateDemographicsGender = TRUE,
                                                          useCovariateDemographicsRace = FALSE,
                                                          useCovariateDemographicsEthnicity = FALSE,
                                                          useCovariateDemographicsAge = TRUE, useCovariateDemographicsYear = FALSE,
                                                          useCovariateDemographicsMonth = TRUE,
                                                          useCovariateConditionOccurrence = TRUE,
                                                          useCovariateConditionOccurrence365d = TRUE,
                                                          useCovariateConditionOccurrence30d = TRUE,
                                                          useCovariateConditionOccurrenceInpt180d = FALSE,
                                                          useCovariateConditionEra = FALSE,
                                                          useCovariateConditionGroup = FALSE,
                                                          useCovariateDrugExposure = FALSE,
                                                          useCovariateDrugEra = TRUE,
                                                          useCovariateDrugEra365d = TRUE, useCovariateDrugEra30d = TRUE,
                                                          useCovariateDrugEraOverlap = FALSE, useCovariateDrugEraEver = FALSE,
                                                          useCovariateDrugGroup = TRUE,
                                                          useCovariateProcedureOccurrence = FALSE,
                                                          useCovariateProcedureOccurrence365d = FALSE,
                                                          useCovariateProcedureOccurrence30d = FALSE,
                                                          useCovariateProcedureGroup = FALSE,
                                                          useCovariateObservation = FALSE,
                                                          useCovariateObservation365d = FALSE, useCovariateObservation30d = FALSE,
                                                          useCovariateObservationCount365d = FALSE,
                                                          useCovariateMeasurement = FALSE,
                                                          useCovariateConceptCounts = TRUE,
                                                          useCovariateRiskScores = FALSE,
                                                          useCovariateInteractionYear = FALSE, useCovariateInteractionMonth = FALSE,
                                                          excludedCovariateConceptIds = c(), includedCovariateConceptIds = c(),
                                                          deleteCovariatesSmallCount = 10)
